import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { isToolCallEventType } from "@earendil-works/pi-coding-agent";

// The allow / ask / deny pattern lists below are GENERATED from the shared
// matrix in agent-scripts/permission_matrix.py by agent-scripts/gen_permissions.py,
// the same source that writes Claude's settings.json permissions and
// opencode.jsonc's permission.bash. Edit the matrix and regenerate; never edit
// the anchored region by hand (`gen_permissions.py --check` fails CI on drift).
//
// Pi ships no built-in permission-prompt system (docs/usage.md's Design
// Principles: "it intentionally does not include built-in MCP, sub-agents,
// permission popups, plan mode, to-dos, or background bash"), so this gate
// re-expresses the matrix for Pi's tool_call event. Only bash is gated:
// opencode's separate `external_directory` permission has no Pi analog.
//
// Pi's one recorded exception: the scripts that have a native Pi tool
// (dev_status.py, grill.py, second_opinion.py, vitals_promotion.py, plus the
// DEVSTATUS_AGENT=1 forms) are NOT allowlisted here. Each is wrapped by an
// extension in pi/extensions/ that replaces raw bash calls; leaving the bash
// pattern allowed would let the model bypass the tool silently. Dropping to
// the default ask makes a direct bash call require confirmation (or fail
// headless), pushing usage toward the tool. The tool's own pi.exec calls never
// go through the tool_call event this gate hooks.
//
// Neutral pattern grammar (see permission_matrix.py): `*` matches any text
// including newlines; a trailing ` *` that is the only `*` also matches the
// bare command; `<dir>` matches exactly one whitespace-free argument. Allow
// patterns match from the start of a segment; ask and deny patterns also match
// after any whitespace inside it, so `FOO=1 git commit` and
// `nice -n 5 ... prune` are still caught.
// <permission-matrix:begin>
// Generated by agent-scripts/gen_permissions.py from
// agent-scripts/permission_matrix.py. Do not edit by hand: edit the
// matrix and regenerate.
export const ALLOW_PATTERNS: string[] = [
  "python3 ~/.agent-toolkit/scripts/settings_seed_drift_check.py *",
  "python3 ~/.agent-toolkit/scripts/bundle_drift_check.py *",
  "python3 ~/.agent-toolkit/scripts/worktree.py *",
  "./scripts/bootstrap-worktree.sh*",
  "scripts/bootstrap-worktree.sh*",
  "./scripts/build-copilot-swarm.sh*",
  "scripts/build-copilot-swarm.sh*",
  "npm install*",
  "npm test*",
  "npm run test*",
  "npm run lint*",
  "npm run typecheck*",
  "npm run format*",
  "git log*",
  "git status*",
  "git diff*",
  "git show*",
  "git ls-files*",
  "git check-ignore*",
  "git add*",
  "git rev-parse*",
  "git branch",
  "git branch --show-current",
  "git branch --list *",
  "git branch -a",
  "git branch -v",
  "git branch -vv",
  "git branch -av",
  "git branch -avv",
  "git checkout -b *",
  "git worktree list *",
  "git worktree add *",
  "git -C <dir> log*",
  "git -C <dir> status*",
  "git -C <dir> diff*",
  "git -C <dir> show*",
  "git -C <dir> ls-files*",
  "git -C <dir> check-ignore*",
  "git -C <dir> add*",
  "git -C <dir> rev-parse*",
  "git -C <dir> branch",
  "git -C <dir> branch --show-current",
  "git -C <dir> branch --list *",
  "git -C <dir> branch -a",
  "git -C <dir> branch -v",
  "git -C <dir> branch -vv",
  "git -C <dir> branch -av",
  "git -C <dir> branch -avv",
  "git -C <dir> checkout -b *",
  "git -C <dir> worktree list *",
  "git -C <dir> worktree add *",
  "uv sync*",
  "uv run pytest*",
  "uv run ruff check*",
  "uv run ruff format*",
  "lsof *",
  "ps *",
  "ls*",
  "pwd",
  "which *",
  "head *",
  "tail *",
  "wc *",
  "sort *",
  "uniq *",
  "grep *",
  "rg *",
  "file *",
  "stat *",
  "du *",
  "df *",
  "date*",
  "whoami*",
  "env",
  "printenv*",
  "cat *",
  "strings *",
  "readlink *",
  "jq *",
  "diff *",
  "echo *",
  "pgrep *",
  "ss *",
  "systemctl status*",
  "systemctl is-active*",
  "systemctl is-enabled*",
];
export const ASK_PATTERNS: string[] = [
  "git commit*",
  "git -C <dir> commit*",
  "git checkout -b * -*f*",
  "git -C <dir> checkout -b * -*f*",
  "git worktree add*-B*",
  "git -C <dir> worktree add*-B*",
  "git difftool*",
  "git -C <dir> difftool*",
  "sort -o *",
];
export const DENY_PATTERNS: string[] = ["python3 ~/.agent-toolkit/scripts/dev_status.py prune*"];
// <permission-matrix:end>

export type PatternMode = "start" | "anywhere";

export function patternToRegExp(pattern: string, mode: PatternMode = "start"): RegExp {
  const escape = (s: string): string => s.replace(/[.+?^${}()|[\]\\]/g, "\\$&");
  // `[\s\S]` rather than `.` so a wildcard also covers literal newlines —
  // only escaped continuations and quoted newlines survive segmentation into
  // a segment, and neither can hide a top-level operator.
  const glob = (s: string): string =>
    s
      .split("<dir>")
      .map((part) => part.split("*").map(escape).join("[\\s\\S]*"))
      .join("\\S+");
  const starCount = pattern.split("*").length - 1;
  const body =
    pattern.endsWith(" *") && starCount === 1
      ? `${glob(pattern.slice(0, -2))}(?: [\\s\\S]*)?`
      : glob(pattern);
  const prefix = mode === "anywhere" ? "(?:[\\s\\S]*\\s)?" : "";
  return new RegExp(`^${prefix}${body}$`);
}

const ALLOW_REGEXPS = ALLOW_PATTERNS.map((p) => patternToRegExp(p));
const ASK_REGEXPS = ASK_PATTERNS.map((p) => patternToRegExp(p, "anywhere"));
const DENY_REGEXPS = DENY_PATTERNS.map((p) => patternToRegExp(p, "anywhere"));

export type Verdict = "allow" | "deny" | "ask";

type ScanState = "normal" | "single" | "double";

/**
 * Quote- and escape-aware scan of one command (assumed trimmed), producing
 * the segments a per-segment allowlist check runs against: operators
 * (`;`, `&&`, `||`, `|`, `&`, newline) split only at top level — outside
 * quotes, unescaped, and not part of a redirection (`2>&1`, `>&2`, `<&0`,
 * `&>`) — while segments keep their original text so the pattern globs
 * match real content. Command substitution (backticks, `$(`, `<(`, `>(`)
 * cannot be resolved statically, so its presence outside single quotes is
 * reported and the caller lands on ask.
 *
 * Deliberately fail-closed wherever bash is subtler than this scan: an
 * unclosed quote or a trailing backslash reports ambiguity, heredoc bodies
 * segment on their newlines (their lines fail the allowlist → ask), and
 * ANSI-C `$'...'` quoting is unmodeled (the scan closes its quote state
 * early, which can only turn quoted text into extra failing segments).
 */
function scanCommand(command: string): {
  segments: string[];
  substitution: boolean;
  ambiguous: boolean;
} {
  const segments: string[] = [];
  let current = "";
  let substitution = false;
  let ambiguous = false;
  let state: ScanState = "normal";

  const endSegment = (): void => {
    const trimmed = current.trim();
    if (trimmed !== "") segments.push(trimmed);
    current = "";
  };

  let i = 0;
  while (i < command.length) {
    const c = command[i]!;

    if (state === "single") {
      if (c === "'") state = "normal";
      current += c;
      i++;
      continue;
    }

    if (state === "double") {
      if (c === '"') {
        state = "normal";
        current += c;
        i++;
        continue;
      }
      // In double quotes bash escapes only " ` \ and newline; before any
      // other character (notably `$` and a backtick) the backslash is
      // literal, so scanning continues and a live substitution after it is
      // still seen (`\\$(x)` triggers, `\$(x)` false-asks — safe direction).
      if (c === "\\" && i + 1 < command.length && ['"', "\\", "\n"].includes(command[i + 1]!)) {
        current += c + command[i + 1]!;
        i += 2;
        continue;
      }
      if (c === "`" || (c === "$" && command[i + 1] === "(")) substitution = true;
      current += c;
      i++;
      continue;
    }

    // normal state
    if (c === "\\") {
      if (i + 1 >= command.length) {
        ambiguous = true;
        break;
      }
      // Escapes the next character unconditionally — including `\;` and a
      // line continuation `\<newline>`, neither of which is a boundary.
      current += c + command[i + 1]!;
      i += 2;
      continue;
    }
    if (c === "'") {
      state = "single";
      current += c;
      i++;
      continue;
    }
    if (c === '"') {
      state = "double";
      current += c;
      i++;
      continue;
    }
    if (
      c === "`" ||
      (c === "$" && command[i + 1] === "(") ||
      ((c === "<" || c === ">") && command[i + 1] === "(")
    ) {
      substitution = true;
      current += c;
      i++;
      continue;
    }
    // A `#` at a word start begins a comment: drop the rest of the line so
    // it cannot manufacture a failing segment.
    if (c === "#" && current.trim() === "") {
      while (i < command.length && command[i] !== "\n") i++;
      continue;
    }
    if (c === ";" || c === "\n") {
      endSegment();
      i++;
      continue;
    }
    if (c === "|") {
      // `||` and `|&` are two-character operator tokens.
      endSegment();
      i += command[i + 1] === "|" || command[i + 1] === "&" ? 2 : 1;
      continue;
    }
    if (c === "&") {
      if (command[i + 1] === ">" || command[i - 1] === ">" || command[i - 1] === "<") {
        // Descriptor redirection (`2>&1`, `>&2`, `<&0`, `&>`, `&>>`) — not a
        // boundary. `&` preceded by a plain argument digit (`sleep 1&echo`)
        // still backgrounds, matching bash.
        current += c;
        i++;
        continue;
      }
      endSegment();
      i += command[i + 1] === "&" ? 2 : 1;
      continue;
    }
    current += c;
    i++;
  }

  if (state !== "normal") ambiguous = true;
  endSegment();
  return { segments, substitution, ambiguous };
}

export function classify(command: string): Verdict {
  const trimmed = command.trim();
  // Empty and operator-only input: nothing runnable, nothing allowlisted — ask.
  if (trimmed === "") return "ask";

  const { segments, substitution, ambiguous } = scanCommand(trimmed);

  // Reduction order: deny anywhere wins, then ambiguity/substitution forces
  // ask, then an ask match on any segment, then allow only when at least one
  // segment exists and every one clears the allowlist (never `[]`'s vacuous
  // every()), else ask.
  if (segments.some((s) => DENY_REGEXPS.some((re) => re.test(s)))) return "deny";
  if (substitution || ambiguous) return "ask";
  if (segments.some((s) => ASK_REGEXPS.some((re) => re.test(s)))) return "ask";
  if (segments.length > 0 && segments.every((s) => ALLOW_REGEXPS.some((re) => re.test(s)))) {
    return "allow";
  }
  return "ask";
}

/**
 * Whether this pi session runs with no human watching it.
 *
 * A swarm worker lives in a herdr tab nobody is looking at, so a confirmation
 * dialog there is a question addressed to no one -- the worker waits forever
 * while `agent_status` still reads "working". So the gate is never armed in
 * such a session, rather than armed and then talked down: swarm-tool.ts
 * spawns each worker tab with `herdr tab create --env PI_AGENT_UNATTENDED=1`,
 * and this is read at module load, before the first tool_call can arrive.
 *
 * This replaces a slash-command handshake (a token, an acknowledgement file,
 * a poll and a deadline) that had to prove the gate came down after the fact.
 * There is nothing to prove now: no prompt to deliver, nothing to time out,
 * and no window in which a worker has been handed work while still armed.
 *
 * What "unattended" means is each gate's own decision, and the two differ on
 * purpose. Here it means allow, except for deny: this gate's "ask" tier is
 * everything outside
 * a narrow allowlist, and a worker that cannot run tests or git is no worker
 * at all. That is also what the swarm historically did by sending /permission-gate
 * off (historically /permission-gate-disable), so it is not a new grant. guard-rails.ts reaches
 * the opposite conclusion for the commands it guards -- it blocks them rather
 * than asking -- and keeps every one of its non-interactive rules armed.
 *
 * It fails closed. Anything but exactly "1" -- unset, empty, "0", "true" --
 * leaves the gate armed, so an ordinary interactive session is unaffected and
 * a typo in the variable name cannot silently disarm anything.
 *
 * Read here rather than shared from one module: pi loads each extension
 * separately, and a value imported across extension files does not reliably
 * reach the loaded instance (see guard-rails.ts, which reads the same
 * variable for itself).
 */
export function agentUnattendedByEnv(env: NodeJS.ProcessEnv = process.env): boolean {
  return env.PI_AGENT_UNATTENDED === "1";
}

/**
 * The gate's state at module load, as a function so it can be tested.
 *
 * The read happens once, at load, rather than per tool_call: an explicit
 * /permission-gate on must be able to re-arm the gate even in an
 * unattended session, which a per-call environment check would silently
 * override.
 */
export function initialGateEnabled(env: NodeJS.ProcessEnv = process.env): boolean {
  return !agentUnattendedByEnv(env);
}

/**
 * Whether an unattended session still enforces the deny tier at load.
 *
 * A deny is a block, not a prompt, so it can never leave a worker waiting on
 * a question addressed to no one -- there is no reason to drop it along with
 * the ask tier. Any explicit human choice afterwards (/permission-gate on|off,
 * /trust-session) replaces this state entirely.
 */
export function initialDenyOnly(env: NodeJS.ProcessEnv = process.env): boolean {
  return agentUnattendedByEnv(env);
}

let enabled = initialGateEnabled();
let denyOnly = initialDenyOnly();

/** Read-only view of the gate, so a caller (or a test) can confirm its state. */
export function isPermissionGateEnabled(): boolean {
  return enabled;
}

/** True while a disarmed (unattended) gate still blocks deny-tier commands. */
export function isDenyOnly(): boolean {
  return !enabled && denyOnly;
}

// No exported setter on purpose. One used to live here ("Exported so
// trust-session.ts can flip this gate") -- but pi evaluates every extension
// in its own jiti registry, so trust-session's imported setter ran against a
// private copy and the loaded gate never saw the flip: /trust-session
// reported success while changing nothing (proven live 2026-09-02).
// Cross-extension toggling now arrives over the shared event bus below.

export default function (pi: ExtensionAPI) {
  // /trust-session broadcasts here (see its comment
  // for why the channel name is a duplicated literal rather than an import).
  // The listener mutates the same module-level `enabled` the tool_call
  // handler reads. Malformed payloads are ignored: a wrong shape must never
  // silently disarm (or spuriously re-arm) the gate.
  pi.events.on("session-trust-changed", (data) => {
    const trusted = (data as { trusted?: unknown } | null | undefined)?.trusted;
    if (typeof trusted === "boolean") {
      enabled = !trusted;
      denyOnly = false;
    }
  });

  pi.on("tool_call", async (event, ctx) => {
    if (!enabled && !denyOnly) return undefined;
    if (!isToolCallEventType("bash", event)) return;

    const command = event.input.command;
    const verdict = classify(command);

    if (!enabled) {
      // Unattended deny-only state: allow and ask both pass through.
      if (verdict === "deny") {
        return { block: true, reason: `Denied by permission-gate: ${command}` };
      }
      return undefined;
    }

    if (verdict === "allow") return;

    if (verdict === "deny") {
      return { block: true, reason: `Denied by permission-gate: ${command}` };
    }

    // "ask" tier. ctx.hasUI is true in TUI and RPC modes, false in print
    // mode (-p) and JSON mode (docs/extensions.md's ExtensionContext) —
    // there is nothing to confirm through in the false case, so block
    // rather than silently letting an unreviewed command run headless.
    if (!ctx.hasUI) {
      return {
        block: true,
        reason: `Blocked by permission-gate (no UI to confirm through in this mode): ${command}`,
      };
    }

    const ok = await ctx.ui.confirm("Run bash command?", command);
    if (!ok) return { block: true, reason: "Blocked by user" };
  });

  pi.registerCommand("permission-gate", {
    description:
      "Toggle bash permission-gate for this session (or: /permission-gate [on|off|status])",
    handler: async (args, ctx) => {
      const mode = args.trim().toLowerCase();
      if (mode === "status") {
        const state = enabled ? "enabled" : denyOnly ? "deny-only (unattended)" : "disabled";
        ctx.ui.notify(`Permission gate is ${state}`, "info");
        return;
      }
      denyOnly = false;
      if (mode === "on" || mode === "enable") {
        enabled = true;
      } else if (mode === "off" || mode === "disable") {
        enabled = false;
      } else {
        enabled = !enabled;
      }
      if (enabled) {
        ctx.ui.notify("Permission gate enabled", "info");
      } else {
        ctx.ui.notify("Permission gate disabled — all bash commands run unconfirmed", "warning");
      }
    },
  });
}
